services:
  # database:
  #   image: postgres
  #   ports:
  #     - 5001:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=chat
  #     - POSTGRES_USER=dkoder
  #     - POSTGRES_PASSWORD=1234

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80

  mysqlservice:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PORT=3306
    ports:
      - 5002:3306
    volumes:
      - phpmyadminvolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_HOST=mysqlservice
    ports:
      - 8080:80
volumes:
  # pgdata:
  phpmyadminvolume:
